name: alga
description: A powerful tool app for all developers.

publish_to: "none"
version: 1.0.4+34-pre

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  # custom packages
  lorem_ipsum:
    path: ./packages/lorem_ipsum
  highlight_textspan:
    path: ./packages/highlight_textspan
  language_textfield:
    path: ./packages/language_textfield
  # py_dict_parser:
  #   path: ./packages/py_dict_parser
  # alga_parser:
  #   path: ./packages/alga_parser

  cupertino_icons: ^1.0.6
  archive: ^3.3.8
  dart_style: ^2.3.1
  uuid: ^3.0.7
  flutter_svg: ^2.0.7
  window_manager: ^0.3.6
  yaml: ^3.1.2
  json2yaml:
    git:
      url: https://github.com/laiiihz/json2yaml
  flutter_markdown: ^0.6.17+2
  url_launcher: ^6.1.14
  animations: ^2.0.8
  flutter_riverpod: ^2.4.0
  sass: ^1.66.1
  file_selector: ^1.0.1
  shelf_static: ^1.1.2
  flutter_highlight: ^0.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  qr_flutter: ^4.1.0
  blurhash_dart: ^1.2.1
  flutter_blurhash: ^0.7.0
  image_picker: ^1.0.4
  device_info_plus: ^9.0.2
  network_info_plus: ^4.0.1
  import_sorter: ^4.6.0
  markdown: ^7.0.2
  pointycastle: ^3.7.3
  pigment: ^1.0.4
  go_router: ^10.1.2
  flutter_colorpicker: ^1.0.3
  image: ^4.0.17
  convert: ^3.1.1
  path: ^1.8.2
  shelf: ^1.4.1
  adaptive_breakpoints: ^0.1.4
  dynamic_color: ^1.6.5
  tuple: ^2.0.1
  multi_split_view: ^2.4.0
  auto_size_text: ^3.0.0
  filesize: ^2.0.1
  riverpod_annotation: ^2.1.5
  file: ^7.0.0
  path_provider: ^2.1.1
  quick_actions: ^1.0.6
  connectivity_plus: ^4.0.2
  flutter_js: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  msix: ^3.15.0
  riverpod_generator: ^2.3.2
  custom_lint: ^0.5.3
  riverpod_lint: ^2.0.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/logo/
    - assets/images/

  fonts:
    - family: Noto Sans Mono
      fonts:
        - asset: assets/fonts/NotoSansMono-Regular.ttf

import_sorter:
  emojis: true
  comments: false
