name: alga
description: A powerful tool app for all developers.

publish_to: "none"
version: 1.0.4+34-pre

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

  # custom packages
  lorem_ipsum:
    path: ./packages/lorem_ipsum
  highlight_textspan:
    path: ./packages/highlight_textspan
  language_textfield:
    path: ./packages/language_textfield
  flutter_js_wrapper:
    path: ./packages/flutter_js_wrapper
  # py_dict_parser:
  #   path: ./packages/py_dict_parser
  # alga_parser:
  #   path: ./packages/alga_parser

  cupertino_icons: ^1.0.5
  archive: ^3.3.7
  dart_style: ^2.3.1
  uuid: ^3.0.7
  flutter_svg: ^2.0.7
  window_manager: ^0.3.4
  yaml: ^3.1.2
  json2yaml:
    git:
      url: https://github.com/laiiihz/json2yaml
  flutter_markdown: ^0.6.15
  url_launcher: ^6.1.11
  animations: ^2.0.7
  flutter_riverpod: ^2.3.6
  sass: ^1.60.0
  file_selector: ^1.0.0
  shelf_static: ^1.1.2
  flutter_highlight: ^0.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  qr_flutter: ^4.1.0
  blurhash_dart: ^1.2.1
  flutter_blurhash: ^0.7.0
  image_picker: ^1.0.0
  device_info_plus: ^9.0.2
  network_info_plus: ^4.0.1
  import_sorter: ^4.6.0
  markdown: ^7.0.2
  pointycastle: ^3.7.3
  pigment: ^1.0.4
  go_router: ^8.2.0
  flutter_colorpicker: ^1.0.3
  image: ^4.0.17
  convert: ^3.1.1
  path: ^1.8.2
  shelf: ^1.4.1
  adaptive_breakpoints: ^0.1.4
  dynamic_color: ^1.6.5
  tuple: ^2.0.1
  multi_split_view: ^2.4.0
  auto_size_text: ^3.0.0
  filesize: ^2.0.1
  riverpod_annotation: ^2.1.1
  file: ^6.1.4
  path_provider: ^2.0.15
  quick_actions: ^1.0.5
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  flutter_flavorizr:
    git:
      url: https://github.com/AngeloAvv/flutter_flavorizr
    version: ^2.2.1
  msix: ^3.16.1
  riverpod_generator: ^2.2.3
  custom_lint: ^0.4.0
  riverpod_lint: ^1.1.6

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/logo/
    - assets/images/

  fonts:
    - family: Noto Sans Mono
      fonts:
        - asset: assets/fonts/NotoSansMono-Regular.ttf

import_sorter:
  emojis: true
  comments: false

flavorizr:
  app:
    android:
      flavorDimensions: "abi"
    ios:

  flavors:
    dev:
      app:
        name: "Alga Dev"

      android:
        applicationId: "tech.laihz.alga.dev"
      ios:
        bundleId: "tech.laihz.alga"

    arm:
      app:
        name: "Alga"

      android:
        applicationId: "tech.laihz.alga.arm"
        customConfig:
          ndk: '{ abiFilter "armeabi-v7a" }'

      ios:
        bundleId: "tech.laihz.alga"

    arm64:
      app:
        name: "Alga"

      android:
        applicationId: "tech.laihz.alga.arm64"
        customConfig:
          ndk: '{ abiFilter "arm64-v8a" }'

      ios:
        bundleId: "tech.laihz.alga"

    x86_64:
      app:
        name: "Alga"

      android:
        applicationId: "tech.laihz.alga.x86_64"
        customConfig:
          ndk: '{ abiFilter "x86_64" }'

      ios:
        bundleId: "tech.laihz.alga"

    universal:
      app:
        name: "Alga"

      android:
        applicationId: "tech.laihz.alga"

      ios:
        bundleId: "tech.laihz.alga"

    aab:
      app:
        name: "Alga"

      android:
        applicationId: "tech.laihz.alga.aab"

      ios:
        bundleId: "tech.laihz.alga"
