name: alga
description: A powerful tool app for all developers.

publish_to: "none"
version: 2.0.1-dev+36

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  # custom packages
  lorem_ipsum:
    path: ./packages/lorem_ipsum
  highlight_textspan:
    path: ./packages/highlight_textspan
  language_textfield:
    path: ./packages/language_textfield
  # py_dict_parser:
  #   path: ./packages/py_dict_parser
  # alga_parser:
  #   path: ./packages/alga_parser

  cupertino_icons: ^1.0.6
  archive: ^3.4.9
  dart_style: ^2.3.2
  uuid: ^4.2.1
  flutter_svg: ^2.0.9
  window_manager: ^0.3.7
  yaml: ^3.1.2
  json2yaml:
    git:
      url: https://github.com/laiiihz/json2yaml
  flutter_markdown: ^0.6.18+2
  url_launcher: ^6.2.1
  animations: ^2.0.8
  flutter_riverpod: ^2.4.6
  sass: ^1.69.5
  file_selector: ^1.0.1
  shelf_static: ^1.1.2
  flutter_highlight: ^0.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  qr_flutter: ^4.1.0
  blurhash_dart: ^1.2.1
  flutter_blurhash:
    git:
      url: https://github.com/MominRaza/flutter_blurhash
  image_picker: ^1.0.4
  device_info_plus: ^9.1.0
  network_info_plus: ^4.1.0
  markdown: ^7.1.1
  pointycastle: ^3.7.3
  pigment: ^1.0.4
  go_router: ^12.1.1
  flutter_colorpicker: ^1.0.3
  image: ^4.1.3
  convert: ^3.1.1
  path: ^1.8.3
  shelf: ^1.4.1
  adaptive_breakpoints: ^0.1.6
  dynamic_color: ^1.6.8
  multi_split_view: ^2.4.0
  auto_size_text: ^3.0.0
  filesize: ^2.0.1
  riverpod_annotation: ^2.3.1
  file: ^7.0.0
  path_provider: ^2.1.1
  quick_actions: ^1.0.6
  connectivity_plus: ^5.0.1
  flutter_js: ^0.8.0
  google_fonts: ^6.1.0
  two_dimensional_scrollables: ^0.0.4
  gal: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  msix: ^3.16.6
  riverpod_generator: ^2.3.7
  go_router_builder: ^2.3.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/logo/
    - assets/images/
    - assets/android/

  fonts:
    - family: Noto Sans Mono
      fonts:
        - asset: assets/fonts/NotoSansMono-Regular.ttf

import_sorter:
  emojis: true
  comments: false
